# GET http://localhost:5000/api/tickets HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjM2NjA4NzdhMmM4ODM4NTU5ZDg0YyIsImlhdCI6MTY3Njg5ODk1NiwiZXhwIjoxNjc5NDkwOTU2fQ.uHWR2Z3d614mRnu7NECZ7VA841qs_SfotYrpGAPI3tE

# POST http://localhost:5000/api/tickets HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjM2NjA4NzdhMmM4ODM4NTU5ZDg0YyIsImlhdCI6MTY3Njg5ODk1NiwiZXhwIjoxNjc5NDkwOTU2fQ.uHWR2Z3d614mRnu7NECZ7VA841qs_SfotYrpGAPI3tE
# Content-Type: application/json

# {
#     "product":"iPhone",
#     "description":"It is faulty"
# }

# GET http://localhost:5000/api/tickets/63f4a5fd6139dc2fc8747623 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjM2NjA4NzdhMmM4ODM4NTU5ZDg0YyIsImlhdCI6MTY3Njg5ODk1NiwiZXhwIjoxNjc5NDkwOTU2fQ.uHWR2Z3d614mRnu7NECZ7VA841qs_SfotYrpGAPI3tE

# PUT http://localhost:5000/api/tickets/63f4a5fd6139dc2fc8747623 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjM2NjA4NzdhMmM4ODM4NTU5ZDg0YyIsImlhdCI6MTY3Njg5ODk1NiwiZXhwIjoxNjc5NDkwOTU2fQ.uHWR2Z3d614mRnu7NECZ7VA841qs_SfotYrpGAPI3tE
# Content-Type: application/json

# {
#     "product": "iPad",
#     "description": "It is not turning on"
# }

# DELETE http://localhost:5000/api/tickets/63f4a5fd6139dc2fc8747623 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjM2NjA4NzdhMmM4ODM4NTU5ZDg0YyIsImlhdCI6MTY3Njg5ODk1NiwiZXhwIjoxNjc5NDkwOTU2fQ.uHWR2Z3d614mRnu7NECZ7VA841qs_SfotYrpGAPI3tE

GET http://localhost:5000/api/tickets HTTP/1.1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjNmM2UwNWFjODE2NjhkOTQ1MjY3NiIsImlhdCI6MTY3Njk4NDk2MCwiZXhwIjoxNjc5NTc2OTYwfQ.d3ahGY-fWsLLP-4F4Xc_wYrkB-IMuic5jKIKipCEYjg